enabled_locales: ["en", "vi"]
client:
  host: "localhost:3000"
users:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
remember: "1"
perpage: 9
gravatar: 80
reset_sent: 2
micropost:
  content:
    maxcontent: 140
picturesize: 5
gravatarsize: 50
resize: 400
picture: "image/jpeg,image/gif,image/png"
sizegravatar: 30
